# Week 1 experiences

*Describe the work you have done this week and summarize your learning.*


I have downloaded and installed R and R studio for my computer. I also did instal GitHub desktop application. R tools are useful for working with large datasets and GitHub is usegul for editing code or project online simultaniously with other authors.  


Working with R is feeling natural, allthough I have some experience using R in advance.  


I had some problems concerning my course diary page. I could not get my updates to show up there. I did manage to solve this problem with help from section 9 in course page. Very nice. I just dont yet know if I have to do this fix allways or just once.  

A new problem appeared. I managed to create two different versions on my course page. Apparently it had something to do with my merged branches in github or something. 

It seem that I have to knit and save the index files with encoding every time. I hope I have misunderstood this point for now. Now it seems that my course diary page does not update at all. Okay. The delay seems to be something like 20 mins or so. I did think it would be more like few minutes. I am also wondering do I have to make changes in the project files to push them to GitHub or can I just save the index file with encoding and push.  

This week i have learned the very basics of R, RStudio and GitHub. The hardest seems to be GitHub but i'm sure it will work out just fine after a week or two.

This course seems to be just what i was looking for.

